qlik-oss/gopherciser

- scenario/actionhandler.go
- scenario/actionhandler_test.go
**Checklist**
Skip validating disabled actions
> Skip validating disabled actions

- elasticstructs/appimportresponse.go
- elasticstructs/collectionserviceitem.go
- scenario/elasticcreateapp.go
- scenario/elasticduplicateapp.go
- scenario/elasticuploadapp.go
**Checklist**
Changed collection create item request flow, `owner` parameter has been deprecated in favor of `ownerId`.
> Update collection create item request

- .circleci/config.yml
- Dockerfile
**Checklist**
Add build and publish of docker image to github packages
> Add build and publish of docker image

- README.md
**Checklist**
Add circleci status badge to Readme.md
> Add circleci status badge to Readme.md

- go.mod
- go.sum
- licenses.txt
- session/syncedTemplate.go
**Checklist**
Fixes an issues that would cause Gopherciser build for WASM to fail on Windows.
google/uuid is a permissive BSD 3-Clause "New" or "Revised" License
https://github.com/google/uuid/blob/master/LICENSE
> Fix/wasm 1.13

- README.md
**Checklist**
Describe how to pull docker image from Github packages
> Add documentation for pulling docker images

- README.md
**Checklist**
Added info that Gopherciser is also included in the QSEST.
> Added info that Gopherciser is also included in the QSEST.

- docs/settingup.md
- elasticstructs/collection.go
- generatedocs/data/actions/elasticpublishapp/description.md
- generatedocs/data/actions/elasticpublishapp/examples.md
- generatedocs/data/groups/groups.json
- generatedocs/data/params.json
- generatedocs/generated/documentation.go
- scenario/actionhandler.go
- scenario/elasticmoveapp.go
- scenario/elasticpublishapp.go
- scenario/elasticuploadapp.go
**Checklist**
Action to publish apps into managed spaces.
> ElasticPublishApp action

- helpers/timeduration_test.go
- scenario/elasticreload.go
**Checklist**
Fix unmarshal bug for poll interval in elasticreload
> Fix unmarshal bug for poll interval in elasticreload

- enigmahandlers/sensedialer.go
- session/resthandler.go
**Checklist**
Improved cookie handling
> Improved cookie handling

- docs/settingup.md
- generatedocs/data/params.json
- generatedocs/generated/documentation.go
- scenario/elasticreload.go
**Checklist**
Add new CREATED status to list of pending statuses for elasticreload. Make reloadlog optional and add debug logging when the reload state changes.
> Update ElasticReload to comply with new API

- session/autocharthandler.go
**Checklist**
Avoid warnings for getting data on auto-chart main object.
> avoid Get data warning for auto-chart main object

- senseobjdef/defaultdefinitions.go
**Checklist**
Add data def for bulletchart.
> Add data def for bulletchart

- scenario/elasticcreateapp.go
**Checklist**
Allow creation of apps without tagging them. The documentation does not need to be updated since it already implies this is possible.
> Allow creation of apps without tagging them

- scenario/deleteodag.go
- scenario/elasticgenerateodag.go
- scenario/generateodag.go
- senseobjdef/defaultdefinitions.go
- senseobjects/listbox.go
- senseobjects/odagtoolbarnavpoint.go
- session/objecthandling.go
**Checklist**
Update ODAG generation actions to work with June 2020
> Update ODAG generation actions to work with June 2020

- docs/README.md
**Checklist**
Update limitations documentation after autochart logic changes.
> update limitations section in README

- generatedocs/README.md
**Checklist**
make more clear document only go generate needed to generate documentation
> make more clear document only go generate needed to generate documentation

- .circleci/config.yml
- go.mod
- go.sum
**Checklist**
Add golang 1.13 build verifying build compatibility
> Add golang 1.13 build verifying build compatibility 

- elasticstructs/datafilesresponse.go
- scenario/elasticopenhub.go
**Checklist**
Several API calls have been updated from limit=30 to limit=24, as well several new additional API calls, as a part of QCS elasticopenhub action.
> Apicompliance/616 Openhub

- docs/settingup.md
- generatedocs/data/actions/listboxselect/description.md
- generatedocs/data/actions/listboxselect/examples.md
- generatedocs/data/groups/groups.json
- generatedocs/data/params.json
- generatedocs/generated/documentation.go
- scenario/actionhandler.go
- scenario/listboxselect.go
**Checklist**
**Add ListBoxSelect action**
Adds a listbox select action for performing selections specifically available for list objects.
Closes #557
> ListBoxSelect Action

- session/resthandler.go
**Checklist**
Enable REST requests without automatically added virtual proxy (when virtual proxy is defined).
This is useful e.g. when sending requests towards non sense environments as part of custom actions.
> Enable REST requests without automatically added virtualproxy

- docs/extending-gopherciser.md
**Checklist**
Add example repo to documentation show casing how to extend gopherciser with custom actions.
> Add example repo to documentation show casing how to extend gopherciser with custom actions

- docs/settingup.md
- generatedocs/data/actions/listboxselect/description.md
- generatedocs/generated/documentation.go
- scenario/actionhandler.go
- scenario/listboxselect.go
- scenario/select.go
**Checklist**
* Move Enum inteface to actionhandler.go
* Implement Enum interface for ListBoxSelectType
> Move Enum interface

- scenario/elasticuploadapp.go
**Checklist**
Updated elasticuploadapp action API with new `fallbackName `parameter in `/api/v1/apps/import?fileId=<fileid>` to reflect the current statue in QCS.
> Elasticuploadapp action update as per issue 624

- scenario/elastichubsearch.go
**Checklist**
Increase hubsearch API limits from 10 to 100 to reflect client side
> Apicompliance/631 ElasticHubSearch changes 

- appstructure/appstructure.go
- config/appstructure.go
**Checklist**
Fixes https://github.com/qlik-trial/gopherciser/issues/633
> Ignore snapshot and snapshotlist in appstructure

- scenario/elasticcreatecollection.go
- scenario/elasticexplore.go
- scenario/elasticuploadapp.go
**Checklist**
Update GET /api/v1/collections call as part of this action
FROM:  GET /api/v1/collections?query=<collectionName>&type=public&-updateAt
TO:  GET /api/v1/collections?query=<collectionName>&limit=20&sort=%2Bname&type=public
> Apicompliance/629 ElasticCreateCollection changes

- session/resthandler.go
**Checklist**
Add POST and GET methods which can include additional headers on the REST requests.
> add GET and POST methods with extra headers options

- scenario/createsheet.go
- senseobjects/sheetlist.go
**Checklist**
Handle rank sometimes being sent as empty string.
**Info**
> Handle rank sometimes being sent as empty string

- scheduler/scheduler.go
**Checklist**
Adds a possibility to call a function on the scheduler to continue on errors.
> Add possibility to continue on errors in scheduler

- session/sessionstate.go
**Checklist**
Nil check current action state before error reporting event websocket failed.
**Info**
> fix potential nilpointer panic

- appstructure/appstructure.go
- config/appstructure.go
- config/getappstructure.go
- senseobjects/sheetlist.go
**Checklist**
Add published/approved meta to sheets in appstructure
**Info**
> Add published/approved meta to sheets in appstructure

- session/resthandler.go
**Checklist**
Improved logging of failed http requests.
**Info**
> Improved logging of failed http requests.

- scenario/reload.go
**Checklist**
Error instead of panic if no connection during reload
**Info**
Closes #675
> Fix panic when no connection during reload

- scenario/elasticopenhub.go
- scenario/elasticreload.go
- session/resthandler.go
**Checklist**
Warning instead of error on requests towards:
* web-notifications
* subscriptions
**Info**
> Set web-notification and subscriptions requests to warn only

- senseobjdef/constraint.go
- session/autocharthandler.go
**Checklist**
* Fix bug with array pointer getting copied when creating instance for autochart.
* Re-write to make it more obvious it's a copy
**Info**
> fix bug with contraints path getting overwritten

- scenario/containertab.go
**Checklist**
Update containertab action `appstructure`  struct tag to changed field name of _objectid_.
**Info**
> fix containertab ObjectID appstructure struct tag

- docs/settingup.md
- generatedocs/data/actions/dosave/description.md
- generatedocs/data/actions/dosave/examples.md
- generatedocs/data/groups/groups.json
- generatedocs/generated/documentation.go
- scenario/actionhandler.go
- scenario/dosave.go
**Checklist**
- Add now action `dosave` to issue app save command to engine.
**Info**
> Add DoSave action

- session/sessionstate.go
- wsdialer/wsdialer.go
**Checklist**
Make sure OnReconnectDone always triggers if defined
**Info**
> Make sure OnReconnectDone always triggers

- session/dataconnectionids.go
- session/sessionstate_test.go
**Checklist**
fix recursive DataConnectionIDNotFoundError causing panic
**Info**
> Fix recursive DataConnectionIDNotFoundError causing panic

- scenario/elasticopenhub.go
**Checklist**
Send qix-datafiles request open successful dc-dataconnections request-.
**Info**
> Bugfix elasticopenhub

- eventws/events.go
**Checklist**
Add resource type and operation for evaluations.
> Add resource type and operation for evaluations

- docs/README.md
- senseobjdef/defaultdefinitions.go
**Checklist**
Add support for getting data for dashboard bundle objects. This does not include interacting with with the objects, such as selecting.
**Info**
> support get data for dashboard bundle

- docs/settingup.md
- generatedocs/data/params.json
- generatedocs/generated/documentation.go
- scenario/containertab.go
- session/containerhandler.go
- session/sessionstate.go
**Checklist**
* Support containers with show conditions
* Automatically switch child if current no longer considered visible
* If no visible child remove current subscription
* Update `containertab` random to only pick among visible children
* error on userdefined containertab switch to non-visible children
**Info**
> Support containers with show conditions

- elasticstructs/evaluation.go
- scenario/elasticopenhub.go
**Checklist**
Update elastic open hub action for API compliance
**Info**
> update elastic openhub for api compliance

- go.mod
- go.sum
**Checklist**
Update enigma-go to latest master (engine 12.852.0)
**Info**
> update to latest enigma master

- appstructure/appstructure.go
- config/appstructure.go
**Checklist**
Ignore alertbookmark objects to avoid failing app structure.
**Info**
> handle alerttbookmark

- config/appstructure.go
**Checklist**
Get app structure: Only warn on objects which get handle 0 and can't be interacted with.
**Info**
> app structure: warning instead of error on objects without interactions

- scenario/elasticexplore.go
> ElasticExplore API updates Dec 2020

- session/artifactmap.go
**Checklist**
Allocate new variable before adding space to artifactmap.
**Info**
> Allocate new variable before adding space to artifactmap

- scenario/connfunchandler.go
**Checklist**
* Change test connection towards elastic to a new URL.
**Info**
> Change test connection towards elastic to a new URL.

- senseobjects/sheetlist.go
**Checklist**
sheet columns and rows sometimes sent as strings from engine.
**Info**
> Handle engine sending strings instead of integers for newly created sheets

- renovate.json
resolves #170 
**Checklist**
Update deprecated renovate config settings
**Info**
> update deprecated renovate config settings

- scenario/elasticopenhub.go
- session/features.go
- session/sessionstate.go
**Checklist**
Add feature flag map to session state to enable logic flows differing depending on feature flags enabled.
**Info**
> Add handling of feature flags

- session/dataconnectionids.go
**Checklist**
Fetch top 10k from qix-datafiles
**Info**
> api-compliance: Fetch top 10k from qix-datafiles

- eventws/events.go
- scenario/elasticreload.go
Make elasticreload api compliant
Add http requests:
GET api/v1/items/ITEMID
GET /api/v1/reloads?appId=APPID
> Elasticreload api-compliance

- senseobjdef/defaultdefinitions.go
**Checklist**
Add sn-video-player as supported object.
**Info**
> Add sn-video-player as supported object.

- helpers/panicrecover.go
- scenario/scenario_test.go
- session/containerhandler.go
**Checklist**
- Handle container object definitions missing `condition` parameter.
- Log stack on panic errors
**Info**
> Handle containers without condition parameter defined in object structure

- enigmahandlers/senseconnect.go
**Checklist**
Remove session name from log entries.
**Info**
> Remove logging of session ID.

- session/resthandler.go
**Checklist**
Add PATCH http method
**Info**
> add http method patch

- buildmetrics/buildmetrics_js.go
**Checklist**
Fix API Prometheus method when running under js.
**Info**
> Update signature for api prometheus dummy method for js

- scenario/uploaddata.go
**Checklist**
Close file after uploading data
**Info**
> Close file after uploading data

- scenario/elasticuploadapp.go
- scenario/uploaddata.go
- tempcontent/tus.go
**Checklist**
Add smart tus-chunksize
Set chunksize to min of filesize & default chunksize.
**Info**
> Set chunksize to min of filesize & default chunksize

- tempcontent/tus.go
> Fix default chunksize bug

- cmd/completion.go
- cmd/execute.go
- docs/README.md
**Checklist**
- [] tests added
Add command line completion
Add a cobra subcommand to generate command line completion scripts for zsh, bash, powershell and fish
**Info**
I have verified it works for zsh, bash and powershell. Any of you guys using fish?
> Add command line completion

- scenario/elasticdeleteapp.go
- session/resthandler.go
**Checklist**
* Update to latest request flow for delete app
* Add Rest helpers for DELETE requests.
**Info**
> Update to latest request flow for delete app

- docs/settingup.md
- eventws/eventhandler.go
- eventws/events.go
- generatedocs/data/params.json
- generatedocs/generated/documentation.go
- scenario/elasticcreateapp.go
**Checklist**
Make elasticcreateapp action api compliant
**Info**
> Apicompliance: elasticcreateapp

- session/features.go
**Checklist**
Add info row log with current feature flags.
**Info**
> log feature flag info row

- session/resthandler.go
- session/resthandler_test.go
**Checklist**
Fix two http client bugs
- Do not remove request parameters when using virtualproxy
- Respect the NoVirtualProxy option in get requests
**Info**
> Fix two http client bugs

- generatedocs/data/params.json
- generatedocs/generated/documentation.go
**Checklist**
Remove deletedata from params.json
**Info**
> Remove deletedata from params.json

- docs/examples/configuration_example.json
- docs/examples/random-qseow-header.json
- docs/examples/random-qseow.json
- docs/examples/random.json
- docs/examples/sheetChangerQlikCore.json
- docs/examples/testjob.json
**Checklist**
Update example scripts.
**Info**
> Update example scripts

- docs/settingup.md
- generatedocs/data/actions/setsensevariable/description.md
- generatedocs/data/actions/setsensevariable/examples.md
- generatedocs/data/groups/groups.json
- generatedocs/data/params.json
- generatedocs/generated/documentation.go
- scenario/actionhandler.go
- scenario/setsensevariable.go
Add a setsensevariable action to change variables in an app
**Info**
> Setsensevariable

- docs/settingup.md
- generatedocs/data/params.json
- generatedocs/generated/documentation.go
- scenario/randomaction.go
- scenario/setsensevariable.go
Fix for RandomAction to work with listboxes.
**Checklist**
Fix for randomaction to include listboxes as selectable objects
Added support for session variables to setsensevariable
**Info**
> Add scriptvariable support for the value of the sensevariable

- scenario/setscriptvar.go
- session/variables.go
> Adjustments to SetScriptVar for better integration with GUI

- scenario/askhubadvisor.go
**Checklist**
AskHubAdvisor action: validate query weights are above 0.
**Info**
> AskHubAdvisor: Query weight must be positive number

- session/syncedTemplate.go
**Checklist**
Support unsigned integers in scriptvar "add" function.
**Info**
> add unsigned integers to parseint

- cmd/helpers.go
- go.mod
- go.sum
- licenses.txt
**Checklist**
Don't check for piped data when running in debugger.
**Info**
> Don't check for piped data when running in debugger

- execution?id=1234
**Checklist**
remove file breaking go get
**Info**
> remove file which shouldn't be included

- config/config.go
**Checklist**
run pre/post hooks with background context not config context, since it would otherwise not run on cancel
**Info**
> Use Background context with timeout for PRE/POST hooks

- session/artifactmap.go
**Checklist**
Add artifactmap lookup functions also for item ID.
**Info**
> add lookup functions for item ID to artifactmap

- metrics/transport.go
**Checklist**
Refactored push metrics URL so it supports path on URL as well
**Info**
Refactored push metrics URL so it supports path on URL as well
> Refactored push metrics URL so it supports path on URL as well

- cmd/execute.go
- generatedocs/pkg/common/common.go
- helpers/datapath.go
- helpers/errors.go
- metrics/transport.go
- scenario/openapp.go
- scenario/scenario_test.go
- scheduler/simple.go
- scheduler/timebuffer_test.go
- scripts/lint.sh
- senseobjdef/constraint.go
- session/objecthandling.go
**Checklist**
Lint upgraded to 1.40.1
**Info**
Lint upgraded to 1.40.1
Corrected lint issues arisen from the upgrade
> Lint upgrade

- go.mod
- go.sum
> update to enigma version containing fix for CVE-2020-26160

- .circleci/config.yml
**Checklist**
Add Test build step for new go version
**Info**
> Add test build for new go version 1.17

- .circleci/config.yml
**Checklist**
Change to Go 1.17 in main build and add 1.16 as test build
**Info**
> switch to go 1.17 as main build

- scenario/clickactionbutton.go
- senseobjects/bookmarklist.go
- senseobjects/currentselections.go
- senseobjects/fieldlist.go
- senseobjects/listbox.go
- senseobjects/loadmodellist.go
- senseobjects/sheet.go
- senseobjects/sheetlist.go
- senseobjects/storylist.go
- senseobjects/variablelist.go
- session/appfunctions.go
- session/autocharthandler.go
- session/objecthandling.go
**Checklist**
switch to using GetEffectiveProperties instead of GetProperties.
**Info**
Tested with "sheetchanger" and "all objects", should probably be validated for not breaking select functionality etc, but that kind of tests should be done next QSEoW release anyways.
> change to use Effective properties instead

- scenario/createsheet.go
**Checklist**
Set two properties on sheet after creating it
**Info**
> add setproperties to createsheet

- session/appfunctions.go
**Checklist**
sheet should use specific GetProperties method
**Info**
> sheet propeties should use specific GetProperties method

- session/containerhandler.go
**Checklist**
Support new setting for default tab in container objects.
**Info**
> Support default tab setting in container object

- logger/regression.go
**Checklist**
Add `qInExtRow` as insignificant value for regression analysis
**Info**
> Add qInExtRow as insignificant value for regression analysis

- logger/regression.go
**Checklist**
Writes a header row with the version of the gopherciser being used
**Info**
> Add gopherciser version in regression log header

- .circleci/config.yml
**Checklist**
Switch github releaser tool from `ghr` to offical `github-release` tool·
**Info**
> Switch github releaser tool 

- globals/globals.go
- session/resthandler.go
- wsdialer/wsdialer.go
**Checklist**
* Add User-Agent header to websocket upgrade requests
* Make User-Agent string configurable by code
**Info**
> add user-agent header also to websocket connections

- docs/README.md
**Checklist**
Update exit code docs
**Info**
> Update exit code docs

- cmd/execute.go
- cmd/exitcodes.go
- docs/README.md
**Checklist**
Return exit code `141` for max errors reached.
**Info**
Decision on adding it as specific code _pending_.
> Return exit code 141 for max errors reached

- cmd/execute.go
- pending/pendinghandler.go
- scheduler/simple.go
- senseobjects/app.go
- senseobjects/interfaces.go
- session/sessionstate.go
**Checklist**
* Switch pending handler to use mutex instead of atomic operation.
* Add Log functions to session state and interface in senseobjects to be able to access log functions in senseobjects package.
**Info**
> Mitigate possible hanging gopherciser

- .circleci/config.yml
**Checklist**
For some reason newly created releases is not returned instantly through github api anymore, workaround with a 60s sleep (tried shorter sleep and did not work)
**Info**
> Testreleaser

- docs/settingup.md
- generatedocs/data/params.json
- generatedocs/generated/documentation.go
- scenario/actionhandler.go
- scenario/askhubadvisor.go
- scenario/helpers.go
- scenario/helpers_test.go
- scenario/smartsearch.go
**Checklist**
Fix internal thinktime GUI defaults
- Marshal default values if zero value in json
- Set smartsearch default to static delay 1s for less confusion
- Change action internal thinktimes to values, no null check needed because zero value is already checked.
- Add GUIDefaults interface
**Info**
> Fix internal thinktime defaults

- generatedocs/data/params.json
- generatedocs/generated/documentation.go
**Checklist**
remove uploaddata params from docs
**Info**
> remove uploaddata params from docs

- session/autocharthandler.go
**Checklist**
Autochart selections check
> Autochart selections check

- scenario/deleteodag.go
**Checklist**
Add support for optional app guid in DeleteOdag function.
**Info**
> Add optional app id parameter to DeleteOdag

- README.md
- docs/vscode/gopherciser.code-snippets
**Checklist**
Add code snippet for VSCode for easy action creation.
**Info**
https://user-images.githubusercontent.com/16015083/165740612-877f1126-169e-4044-92f9-d7fa6401b443.mov
> Add VSCode snippet for easy action creation

- docs/settingup.md
- generatedocs/data/params.json
- generatedocs/generated/documentation.go
- scenario/reload.go
**Checklist**
Add possibility to disable save app in reload action 
**Info**
> Add possibility to disable save app in reload action

- scenario/objectsearch.go
**Checklist**
Add missing GUI settings for object search.
**Info**
> Add GUI components for object search

- helpers/timeduration_test.go
- scenario/actionhandler.go
- scenario/randomaction_test.go
- scenario/sheetchanger.go
- scripts/lint.sh
**Checklist**
* Update linter version
* Fix lint warnings
**Info**
> Update linter version

- structs/odag.go
**Checklist**
This resolves an issue which would prevent DeleteOdag from working.
**Info**
DeleteOdag still works the same in QSEfW except one of the fields had changed from a string to a struct - but we weren't using it anyway. Went ahead and cleaned up all struct properties that are not actively used by the actions.
> [bugfix] DeleteOdag with May 2022

- scenario/setscript.go
**Checklist**
Automatically save app after setting load script. (same as client does)
**Info**
> add automatic save of app after setting load script

- .circleci/config.yml
**Checklist**
Dependency cache was set uncorrect in circleci script
**Info**
> fix circleci script

- session/resthandler.go
**Checklist**
Combine performRestCall and postwithreader methods to one method
**Info**
> Combine performRestCall and postwithreader methods to one method

- cmd/script.go
**Checklist**
Add exit code when script validate command fail validation
**Info**
> Add exit code when script validate command fail validation

- session/resthandler.go
> Add `HEAD` http method

- docs/settingup.md
- enigmahandlers/senseconnect.go
- enigmahandlers/topichandler.go
- generatedocs/data/actions/changestream/description.md
- generatedocs/data/actions/changestream/examples.md
- generatedocs/data/actions/openhub/description.md
- generatedocs/data/groups/groups.json
- generatedocs/data/params.json
- generatedocs/generated/documentation.go
- scenario/actionhandler.go
- scenario/changestream.go
- scenario/openhub.go
- session/sessionstate.go
**Checklist**
Changes to api compliance for openhub. This includes splitingt openhub into two actions.
Openhub - any apps in "myspace" can be used, not always clear what apps are in this request, but will include, "my work", "favorites" and "published" sections, also some apps from the separate streams. 
ChangeStream - only apps from the selected stream.
**Info**
> [Apicompliance] openhub

- enigmahandlers/senseconnect.go
- logger/entry.go
- senseobjects/interfaces.go
- session/resthandler.go
- session/sessionstate.go
**Checklist**
Add trace ID from response header to metrics message
**Info**
> Add trace ID from response header to metrics message

- eventws/events.go
**Checklist**
Add sharing task resource type and operation
**Info**
> Add sharing task resource type and operation

- config/appstructure.go
- config/appstructure_test.go
- config/getappstructure.go
**Checklist**
* Add function to Get appstructure in mem.
* Categorize warnings from app structure with warning type returned when getting the structure.
**Info**
> Add in-mem Get app structure method

- enigmahandlers/senseconnect.go
- wsdialer/wsdialer.go
**Checklist**
* Better discover websocket closed instantly after dial finished with no error
* Recycle gobwas bufio buffer
**Info**
> Discover instant disconnect during connection attempt

- .circleci/config.yml
- scenario/actionhandler.go
- scripts/lint.sh
**Checklist**
* Always use latest version of go linter
* Set Go 1.19 as default build
* Add test build for 1.20
**Info**
> Update Linter and Go versions

- buildmetrics/buildmetrics.go
- cmd/execute.go
- docs/README.md
- metrics/transport.go
**Checklist**
API metrics optional with reworked metrics arguments
**Info**
Replaced metricsport with metricslevel and metricsaddress with metricstarget. This allows api metrics to be turned on or off at will
> API metrics optional

- session/sessionstate.go
**Checklist**
Reset custom states inbetween iterations for reuseusers=true
**Info**
> Reset custom states on session state

- scenario/clickactionbutton.go
**Checklist**
Evaluate action button expressions
**Info**
> Evaluate action button expressions

- config/appstructure.go
- config/getappstructure.go
**Checklist**
Expose Appstructure Settings so they can be used by tools dependents.
> Expose GetAppStructureSettings

- .circleci/config.yml
- go.mod
required by dependency, remove test on other go versions
**Checklist**
**Info**
> Set go version to 1.20

- .circleci/config.yml
**Checklist**
Add CI Build for Go version 1.21
**Info**
> add test build for GO 1.21

- scenario/changesheet.go
- scenario/createbookmark.go
- scenario/generateodag.go
- scenario/openapp.go
- senseobjects/app.go
- senseobjects/appspropslist.go
- senseobjects/interfaces.go
- senseobjects/variablelist.go
- session/sessionstate.go
**Checklist**
Changes for API compliance with latest Sense version
**Info**
> Apicompliance 1288 - Open App

- scenario/openapp.go
**Checklist**
ignore error for GetScriptEx request on openapp
**Info**
> ignore error for GetScriptEx on openapp

- senseobjdef/defaultdefinitions.go
**Checklist**
Add support for `sn-text` object.
**Info**
> Add support for sn-text

- senseobjdef/defaultdefinitions.go
**Checklist**
Add support for layout container object and it's children.
**Info**
> Add support for layout object and it's children

- session/objecthandling.go
**Checklist**
Log hypercube sub errors (measure,dimension, minichart) as warnings. Warnings will be the first step to gather data of what type of errors, and how frequent. This might later be upgraded to be logged as an error.
**Info**
> Handle hypercube sub errors as warnings

- session/layouthandler.go
**Checklist**
* Small redesign of layout container handler to cover children not being calculated correctly in some edge cases.
**Info**
> Redesign layout container handler

- session/objecthandling.go
**Checklist**
Report errors on dimension and measure level as errors, unless it's a calculation condition.
**Info**
> Report sub hypercube errors as errors unless calc cond

- .circleci/config.yml
> set 1.21 as main go version for circleci

- connection/connection.go
- scenario/reload.go
**Checklist**
* Fix bug in GetURL function
* Refactor reload action + add function which could be called from other actions.
**Info**
> Refactor `reload`

- scenario/reload.go
**Checklist**
Add support to pass a context to reload function
**Info**
> Support use of context for reload

- eventws/events.go
**Checklist**
Add resource type for reporting task added to events
**Info**
> Add resource type for reporting task added to events

- session/resthandler.go
**Checklist**
Minor bugfix changing net.Dialer timeout to be configured by script timeout.
**Info**
> Set the net.Dialer timeout to script timeout

- scenario/connfunchandler.go
- scenario/openapp.go
**Checklist**
Minor refactor of open app action
* Remove function connection to `OpenAppSettings` for functions not using settings. 
* Separate session object creation etc into a `DoPostOpenAppRequests` function
**Info**
> Openapp refactor

- config/appstructure.go
- config/getappstructure.go
- go.mod
- go.sum
- helpers/math.go
- wsdialer/wsdialer.go
**Checklist**
* Add option to truncate titles and descriptions in appstructure to a defined value to avoid unnecessary memory impact.
* Workaround for engine ws bug
**Info**
> Option to truncate appstructure

- scripts/generateChangeLog.sh
**Checklist**
Improved script for generating change log, fixes bug where release would be compared to latest release in repo instead of previous release before current. (E.g. v0.21.0 vs 0.20.2 instead of v0.20.1 vs v0.20.2 when releasing patch v0.20.2 patch with a later release existing) 
**Info**
> improved changelog generator

- config/getappstructure.go
**Checklist**
Add option to disable warning logs during app structure
**Info**
> Add option to disable warning logs during app structure

- config/getappstructure.go
**Checklist**
Bugfix: get appstructure disable logs flag
**Info**
> Bugfix: get appstructure disable logs flag

- docs/vscode/gopherciser.code-snippets
- helpers/errors_test.go
- scenario/select.go
- statistics/samplecollector_test.go
**Checklist**
* Add tabbable package + add displayname to paramter example
* Fixes some linting issues found by new linter version
**Info**
> Update action code snippets for vscode.

- session/resthandler.go
**Checklist**
Fix trace id header not always being discovered correctly when logging traffic metrics
**Info**
> Fix trace id header not always being discovered correctly when logging traffic metrics

- config/config.go
- scenario/actionhandler.go
- scenario/iterated.go
- scheduler/customscheduler_test.go
- scheduler/scheduler.go
- scheduler/simple.go
**Checklist**
* Add `ValidateActionForScheduler` inteface for actions, where an action can give error or warning based on scheduler type
* Add `onIterationFinished` callback to `StartNewUser` to common scheduler part to be executed on each finished thread iteration.
**Info**
> Enhancements for custom schedulers

- session/resthandler.go
**Checklist**
bugfix: a few REST helpers (OptionsSync, OptionsSyncWitCallback, PostSyncWithCallback, PostSync) was not returning error correctly
**Info**
> Bugfix for some REST request

- helpers/BufferPool.go
- session/resthandler.go
- wsdialer/wsdialer.go
**Checklist**
needs REST refactor to work probably so reverting change
**Info**
> remove global buffer usage for readall

- licenses.txt
**Checklist**
Updated license attribution for dependencies
**Info**
> update license attribution

- config/config.go
**Checklist**
Skip invoking IsActionValidForScheduler inface for disabled actions
**Info**
> skip IsActionValidForScheduler validation for disabled actions

- .circleci/config.yml
- go.mod
**Checklist**
Bump required GO version to 1.23
**Info**
> bump required go version to 1.23

- go.mod
- go.sum
**Checklist**
patch security issue CWE-770
**Info**
> patch security issue CWE-770

- session/resthandler.go
**Checklist**
Support more streaming content-types for traffic metrics log.
**Info**
> Support streaming metrics log for more content types

- session/appselection.go
- session/objecthandling.go
**Checklist**
* Don't consider "7005 calc cond" hyper cube error an error for GetTreeData
* small refactor of unused parameters
**Info**
> Support Treedata calculation condition

- config/config.go
- helpers/datapath.go
- scenario/select.go
- session/objecthandling.go
**Checklist**
Fix new linter warnings due to updated linter version.
**Info**
> fix issues with new linter

- .circleci/config.yml
**Checklist**
Remove setting VER env var in "Build Docker image" step as no longer needed and breaks flow
**Info**
> Fix "Build Docker image" CI step 

- metrics/transport.go
**Checklist**
Changes for prometheus pushed metrics
* automatically add `app=gopherciser` group unless overriden by -g cli command
* Add scheduler metrics
* Add cpu metrics
Effectivly adds the following counters on push to prometheus gateway
```
go_sched_goroutines_goroutines: Count of live goroutines. Sourced from /sched/goroutines:goroutines
go_sched_latencies_seconds: Distribution of the time goroutines have spent in the scheduler in a runnable state before actually running. Bucket counts increase monotonically. Sourced from /sched/latencies:seconds.
go_sched_pauses_stopping_other_seconds: Distribution of individual non-GC-related stop-the-world stopping latencies. This is the time it takes from deciding to stop the world until all Ps are stopped. This is a …
```
> Add scheduler and CPU metrics to prometheus pushed metrics

- .circleci/config.yml
- Makefile
- scripts/build.sh
- scripts/pack.sh
**Checklist**
* Add arm64 linux binaries
* Add arm64 osx binaries
* Remove x64 osx binaries
**Info**
> Add arm64 linux and osx binaries to published releases

- helpers/errors.go
**Checklist**
Add Ranked error helper
**Info**
> Add Ranked error helper

- session/appselection.go
> make sure to set name and id when using app selection "current"
