metrics/custom.go

Some longer running actions require additional buckets in order to gain visibility into latencies.

Adding 1s and 6s buckets to prometheus metrics

---

metrics/transport.go

Using real context to shutdown metrics HTTP server. A nil context is not safe towards the http package and will on occasion cause panic
**Checklist**
Using real context to shutdown metrics HTTP server. A nil context is not safe towards the http package and will on occasion cause panic

Using real context to shutdown metrics HTTP server. 

---

metrics/custom.go
metrics/transport.go

It's conventional to have a `*_build_info` metric (a gauge always set to `1`), with labels to indicate the current-running version. See https://www.robustperception.io/exposing-the-software-version-to-prometheus for more information on this convention.
We had some confusion around which version was running (due to missing metrics), and this would've helped us troubleshoot faster.
Signed-off-by: Dave Henderson <David.Henderson@qlik.com>

metrics: Add gopherciser_build_info metric

---

scenario/select.go
session/defaulthandler.go

**Checklist**
avoid nilpointer exception when using objects without select definitions in select action

avoid nilpointer exception when using objects without select definitions in select action

---

connection/jwtconnection.go

Having `"mode":"jwt"` without any settings for JWT connection resulted in panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9b122f]
goroutine 1 [running]:
...
```
Now gives the following error
```JSONValidateError: ConnectionSettings validation failed: no JWT settings defined```
**Checklist**
Avoid nil pointer panic in jwtconnection validation

avoid nilpointer panic in jwtconnection validation

---

scenario/actionhandler.go

**Checklist**
Don't rename action on reconnected action of type thinktime, also when the settings are a pointer.

Don't rename action on reconnected action of type thinktime

---

scenario/elasticreload.go

**Checklist**
Log elastic reload duration consistently as milliseconds to make it easier to parse by analyzer.

Log elastic reload duration consistently as milliseconds

---

docs/settingup.md
generatedocs/data/params.json
generatedocs/generated/documentation.go
scenario/elasticexplore.go

**Checklist**
Updated both elasticexplore action API from limit=30 to limit=24 to reflect the current statue in QCS.  Also updated the API call change when tag drop down is selected (only seen when the tag parameter is provided in scenario and thus filter by collectionID)

Apicompliance/617 Elasticexplore changes

---

go.mod
go.sum

**Checklist**
andrewmostello's branch has been merged to go-tus master, remove go.mod replace of this dependency and update to latest go-tus master.

Remove go-tus dependency replace as PR has been merge to master

---

scheduler/scheduler.go

**Checklist**
Bugfix: If timebuffer `onerror` was set it would wait inbetween each action (bug introduced in re-connect logic merge, not affecting any released versions).

only trigger timebuffer.wait(errors==true) if there was an error

---

appstructure/appstructure.go
enummap/enummap.go
profile/profile.go
scenario/elasticdeleteapp.go
scenario/elasticexplore.go
scenario/listboxselect.go
scenario/publishsheet.go
scenario/randomaction.go
scenario/select.go
scheduler/scheduler.go
senseobjdef/constraint.go
senseobjdef/senseobjdef.go
session/appselection.go
session/resthandler.go
users/usergenerator.go

Errors returned by the other constructor tended to be ignored when
initializing global variables. When passing an invalid map to the
constructor, early panics are preferable to nil pointer dereferences
later during execution.
**Checklist**
Descriptive text which can be used on the squash commit message to master.

Add and use an enum constructor with panic

---

.github/PULL_REQUEST_TEMPLATE.md

This is done to keep squash commit message clean, which makes it easier
to review.
Also:
* Absolute link to commit message format convention
**Checklist**
Add info section to pull request template
This is done to keep squash commit message clean, which makes it easier to review.
**Info**
When on it, I changed the link to commit message format conventions to an absolute link. The generated link was the wrong one in this message.
The descriptive text for squash commit message was also reworded to encourage commit message to be a part of the review process.

Add info section to pull request template

---

scenario/deletedata.go
scenario/elasticopenhub.go
scenario/uploaddata.go

**Checklist**
If no connection ID is returned in ElasticOpenHub, throw a warning rather than an error. Instead, retry the fetch when doing an upload or deleting a file (client does this upon entering DLE). An error will still be thrown if it fails at this point.

Make qID fetch in elasticopenhub optional

---

connection/wsconnection.go
scenario/openapp.go
session/sessionstate.go
wsdialer/wsdialer.go

**Checklist**
Use hostname without port when looking up header
**Info**
bugfix is the change in  `session/sessionstate.go` the rest is minor refactoring I left in.

make sure not to include port when looking up header

---

eventws/events.go
scenario/elasticreload.go

**Checklist**
Use new result event for reload instead of reload.ended.
**Info**
This is still not in an `eventing` release, (and thusly not yet tested). Will wait for new `eventing` version before testing/merging.

use new reload service result event instead of reload.ended

---

cmd/objdef.go
config/appstructure.go
docs/sense-object-definitions.md
helpers/datapath.go
helpers/datapath_test.go
helpers/jsonhelpers.go
helpers/jsonhelpers_test.go
scenario/clickactionbutton.go
scenario/elasticreload.go
scenario/helpers.go
senseobjdef/constraint.go
senseobjdef/constraint_test.go
senseobjdef/defaultdefinitions.go
senseobjdef/senseobjdef.go
senseobjdef/senseobjdef_test.go
session/autocharthandler.go
session/objecthandling.go

**Checklist**
Fix an issue where some linecharts yield a hypercube error
**Info**
Change lookup for whether a linechart is considered continuous, and therefore needs to be fetched with GetHyperCubeContinuousData.
Change constraint to be an array, where each constraint needs to be fulfilled. Throw an unmarshal error if an object definition file of the old format is used.

Fix an issue where some linecharts yield a hypercube error

---

generatedocs/pkg/doccompiler/compile.go

**Checklist**
Enable doccompiler to partially overload docentry
This makes it possible to of overload just one of examples.md or description.md when generating documentation.
**Info**

Enable doccompiler to partially overload docentry

---

cmd/execute.go
cmd/helpers.go
cmd/script.go
docs/README.md
helpers/datapath.go
helpers/datapath_test.go

**Checklist**
Add possibility to override script values
**Info**
https://github.com/qlik-oss/gopherciser/blob/enhancement/536-ScriptOverrides/docs/README.md#using-script-overrides

Add possibility to override script values

---

.circleci/config.yml

**Checklist**
Move to go 1.15 for artifact producing builds as this has been stable.
**Info**

switch to go 1.15 as mainline, set 1.14 as build test

---

connection/connection.go
helpers/BufferPool.go
scenario/uploaddata.go
session/resthandler.go
session/sessionstate.go
session/syncedTemplate.go

**Checklist**
Use a pool to decrease allocation of memory when using buffers.
**Info**
Also tried using jsoniter "fastest" mode, but made basically no difference to mem or cpu.

add pooled buffers

---

scenario/applybookmark.go
scenario/applybookmark_test.go
scenario/clickactionbutton.go

**Checklist**
* Add option to apply selections only in `applybookmark` action.
* Bugfix: Change click button apply bookmark action to not change sheet.
**Info**

Add option to apply selections only in `applybookmark` action.

---

connection/wsconnection.go
wsdialer/wsdialer.go

**Checklist**
- `wsconnect` version of websocket connection did not, as more correctly done by the `jwtconnection` version, set a deadline on the connect context.
- Adding a default 1 minute deadline for any custom connect functions which hasn't a deadline in context when gopherciser is used as a library.
**Info**

Make sure ws connect context has a deadline

---

main.go

**Checklist**
Add /debug/pprof endpoint to tool when running a http listener (currrently done with the --metrics flag) for debugging purposes. Should not affect anything other then slightly bigger binary unless listener is running and endpoint accessed.
**Info**

add /debug/pprof endpoint when running tool with --metrics flag

---

cmd/execute.go
cmd/helpers.go

**Checklist**
Add code to handle expected data on stdin when running in cygwin since chardevices are not detected properly by golang.
**Info**

Bugfix: Windows binary hanging in cygwin

---

helpers/stringbool.go

**Checklist**
string "boolean" from engine under certain conditions sent as "0" instead of "False".
**Info**

"stringbools" can sometimes be sent as "0" instead of "False"

---

buildmetrics/buildmetrics.go
buildmetrics/buildmetrics_js.go
metrics/custom.go
metrics/transport.go
session/resthandler.go
session/resthandler_test.go

**Checklist**
Add a prometheus SummaryVec and Histogram for duration per HTTP-level API calls including path, method and status code. Limitation: only aggregates results to one level after "api/v1", e.g.
GET https://test:9001/api/v1/evaluations -> "api/v1/evaluations", GET, 200
POST https://test:9001/api/v1/evaluations/abc123 -> "api/v1/evaluations", POST, 201
GET https://test:9001/api/dcaas -> no reporting

Add prometheus metrics for API calls

---

docs/README.md
enigmahandlers/enigmaobject.go
scenario/select.go
senseobjdef/defaultdefinitions.go
senseobjdef/senseobjdef.go
session/objecthandling.go

**Checklist**
Add support for getting data for `sn-grid-chart`.
**Info**
Saving tree data pages has been added in this PR, however two steps still left to be able to support `select` in grid chart
* Add support for hypercube tree mode in `getpossible` part of select function.
* Add support for sending `SelectPivotCells` select request using the saved tree data pages.
The `allvalues` part of getting data might need re-evaluation in case we add more objects based on tree data in the future. Current will send correct requests for grid charts.

Add support for grid charts

---

docs/settingup.md
generatedocs/data/params.json
generatedocs/generated/documentation.go
scenario/elasticmoveapp.go

**Checklist**
Make elasticmoveapp navigate to space by default

Make elasticmoveapp navigate to space by default

---

scenario/randomaction.go

**Checklist**
* Don't include objects without dimensions for random selections using randomaction, e.g. tables with only measures.
**Info**
Before:
```bash
2021-03-04T10:20:35+01:00 Err<0> Warn<0> ActvSess<0> TotSess<0> Actns<0> Reqs<0>
TotErrors<2> TotWarnings<0> TotActions<7> TotRequests<40> Duration<2.634072s>
1 error occurred:
Failed to get cardinal for object<ZmqVAW>: object<ZmqVAW> does not contain a dimensionlist
```
Now:
```bash
2021-03-04T10:21:04+01:00 Err<0> Warn<0> ActvSess<0> TotSess<0> Actns<0> Reqs<0>
TotErrors<0> TotWarnings<0> TotActions<8> TotRequests<49> Duration<2.8247619s>
```

only do random selection in object with at least one dimension

---

connection/connection.go
connection/jwtconnection.go
connection/wsconnection.go
docs/settingup.md
generatedocs/data/params.json
generatedocs/generated/documentation.go
scenario/connfunchandler.go
scenario/openapp.go
scenario/openhub.go

**Checklist**
Add `unique` parameter to `openapp` for forcing unique engine session not re-using previous session state for user.
**Info**

Add `unique` parameter to `openapp` for forcing unique engine session.

---

scenario/openhub.go

**Checklist**
Change `Openhub` insights request to warnings instead of errors.
**Info**

warn instead of error on insights request on openhub

---

enigmahandlers/senseconnect.go
scripts/lint.sh

**Checklist**
Correct stall value for "WS response stall" logging
**Info**

correct value for WS Response stall logging

---

scripts/docbuild.sh

**Checklist**
Latest pandoc version cannot generate docs correctly, lock to version 2.15
**Info**

latest pandoc broken, lock to older 2.15 version

---

session/objecthandling.go

**Checklist**
Better support calculation conditions for charts with separate data requests.
**Info**
```bash
λ ~/dev/qlik-oss/gopherciser/ bugfix/954-CalcCondition* make quickbuild &&  ./build/gopherciser_osx x -c ./localtests/rd-ajh-openreloadanalyzer.json
GO111MODULE=on go build -mod=readonly -o  ./build/gopherciser_osx
2021-11-22T16:33:53+01:00 Err<0> Warn<0> ActvSess<0> TotSess<0> Actns<0> Reqs<0>
TotErrors<0> TotWarnings<1> TotActions<4> TotRequests<103> Duration<2.373589499s> 
λ ~/dev/qlik-oss/gopherciser/ bugfix/954-CalcCondition* grep -E "\twarning\t" ./logs/$(ls -t ./logs | head -n 1)                                    
2021-11-22T16:33:55.742584+01:00        changesheet             4       warning         object<BSpwem>: object has unsatisfied …
```

Better support calculation conditions in some charts

---

renovate.json

**Checklist**
Our postupgrade commands no longer allowed. Using new options for go, will run go mod tidy and automatically update import paths on mayor upgrades, but will not run `go mod verify` (which will likely cause tests to fail, but see no better options to use).
**Info**

custom command no long allowed, using new postUpdateOptions

---

docs/examples.md
docs/settingup.md
generatedocs/pkg/genmd/generate.go

**Checklist**
makes output by pandoc look better + still works with github
**Info**

use <hr> instead of --- in markdown documentation for separator

---

scenario/askhubadvisor.go
scenario/helpers.go
scenario/helpers_test.go
scenario/smartsearch.go

This affects askhubadvisor and smartsearch. The reason for making the
check for deafults and nil is that the gui produces a json object with
static thinktime 0 by default, which is an invalid thinktime.
**Checklist**

Use default thinktime if default thinktime settings or nil

---

docs/sense-object-definitions.md

**Checklist**
Scatter plot is now sending binned data request at break point 2000 instead of 1000.
**Info**

change scatterplot binned breakpoint to new default of 2000

---

docs/settingup.md
generatedocs/data/params.json
generatedocs/generated/documentation.go
scenario/publishsheet.go
scenario/publishsheet_test.go

**Checklist**
Add option to ignore publishing already published sheets
- Add some sheet access debug logging
- Decorate publish sheet error
**Info**
Publishing a public sheet give a generic access denied error, which was hard to trace. Some exported apps can have public sheets when uploaded again, which lead to the finding of this issue. I have not seen this behavior until this week, have you guys seen it before or is it new?

Add option to ignore publishing already published sheets

---

cmd/script.go

**Checklist**
Add option to print result JSON to stdout with validate command. All other messages are printed to stderr so 
```bash
gopherciser s v -c script.json -p > result.json
```
will have the json after unmarshal (which can be diff'ed towards original)
**Info**

add option to print result json to validate command

---

connection/connection.go
connection/jwtconnection.go
connection/wsconnection.go
enigmahandlers/senseconnect.go
enigmahandlers/senseconnect_test.go
enigmahandlers/topichandler.go
globals/constant/topics.go
scenario/openapp.go
session/appfunctions.go
session/sessionstate.go
wsdialer/wsdialer.go

**Checklist**
* Add reconnect errors to current state if existing, instead of separate error log
* Only allow one reconnect function on websocket reconnect.
* Rewrite connect/re-connect to look at session_created, session_attached pushed messages
**Info**

WS Reconnect changes

---

.circleci/config.yml
session/appselection.go
session/appselection_test.go

**Checklist**
* Add Lookup in artifactmap also for guid from list and guid from file
* Add test build for Go 1.22
**Info**

Bugfix artifactmap using GUID from list or file

---

helpers/fuzzyvalues.go

**Checklist**
Support float64 for fuzzyint helper
**Info**

Support float64 for fuzzyint

---

.github/dependabot.yml
renovate.json

**Checklist**
Switch to dependabot instead of renovate
**Info**
renovate seems to have stopped doing PR's and don't have access to config the app.

Switch to dependabot instead of renovate

---

cmd/execute.go

**Checklist**
Now supports log file .ConfigFile variable with multiple .'s in name
**Info**

Bugfix: log file .ConfigFile variable with multiple .'s in name

---

session/resthandler.go

**Checklist**
Add support for more rest methods:
PostSync
PostSyncWithCallback
OptionsAsync
OptionsAsyncWitCallback
OptionsSync
OptionsSyncWitCallback
**Info**

add Post Sync and Options async + sync, with and without callback

---

session/resthandler.go

**Checklist**
When a response is an http2 event stream the normal traffic metric will measure response time to first response. This adds an additional traffic metric with the response time until stream end.
**Info**

add specific traffic metric entry for event streaming

---

helpers/BufferPool.go
session/resthandler.go
wsdialer/wsdialer.go

**Checklist**
Move ReadAll function using global pool buffer to helpers
Use ReadAll function instead of io.ReadAll for decrease memory allocation for REST handler and WS communication.
**Info**
mem profiling example for 10K users logging in and staying connected.

Use custom ReadAll using globalbuffer for REST handler

---

config/config.go
scheduler/scheduler.go
senseobjdef/defaultdefinitions.go
session/narrativeshandler.go
session/objecthandling.go
session/resthandler.go

**Checklist**
Support nl insights (narrative) objects 
**Info**

Support nl insights objects

---

metrics/transport.go

**Checklist**
Remove force added `app` group from pushed prometheus metrics again, instead add `gopherciser` name space to cpu metrics
**Info**

Use gopherciser namespace for pushed prometheus cpu metrics

---

.circleci/config.yml
.github/workflows/check-generate-docs.yaml
.github/workflows/publishwiki.yaml

**Checklist**
```
* Bumps circleci docker to large
* Bumps default build to Go 1.24
* Add permissions field to github actions
```
**Info**

Default build to Go 1.24, bump circleci resources
